language : node_js

addons:
  sonarcloud:
    organization: "doppelganger9-github"

node_js :
 - lts/*

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
 - npm ci

script:
 - npm run prettier:check
 - npm run test:vulnerabilities
 - npm test
 - npm run coveralls
 - npm run test:mutate
 - sonar-scanner -Dsonar.projectKey=doppelganger9_fruit-basket -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.exclusions=node_modules/**/*,coverage/**/*,reports/**/* -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
