on: push
name: CI
jobs:
  build:
    name: npm build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci
    - run: npm test
    - run: npm run test:vulnerabilities
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - run: npm run test:mutate
      env:
        HAS_JOSH_K_SEAL_OF_APPROVAL: "true"
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        TRAVIS_BRANCH: '"${GITHUB_REF}"'
        TRAVIS_PULL_REQUEST: "false"
        TRAVIS_REPO_SLUG: '"${GITHUB_REPOSITORY}"'
    - run: npm run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        COVERALLS_SERVICE_NAME: Github Actions main.workflow
    - run: npm run prettier:check
    - run: npm start
